# Generated by Django 3.1.6 on 2021-05-11 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartao')], max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_entregue', models.DateField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('endereco_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
                ('desconto', models.IntegerField()),
                ('categoria', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rastreamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=100)),
                ('data_esperada', models.DateField()),
                ('codigo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=64)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('produtos', models.ManyToManyField(to='ecommerce.Produto')),
            ],
        ),
    ]
